# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SpoyrV6L7KQzmE8i69Rfo4fyoMZDx1Ej
"""

a, b = map(int, input('정수 두개 입력> ').split())
a, b